daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
  - help wanted
  - don't close
staleLabel: inactive
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed in 7 days if no further activity occurs. Thank you
  for your contributions.
  
- Up Devs 💖
closeComment: true
