version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    labels:
      - "update: npm"
    schedule:
      interval: "daily"

    pull-request-branch-name:
      separator: "-"
