blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/PhW2XJa2yy
    about: Please visit our Discord server for questions and support.
  - name: @BrawlStars Twitter
    url: https://twitter.com/BrawlStars
    about: Ask API releated questions to the dev team on Twitter
