name: Pull Request Approval

on: [pull_request, pull_request_review]

jobs:
  label-approved:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://tiangolo/label-approved:0.0.2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        config: >
          {
            "review: approved":
              {
                "number": 1,
                "await_label": "review: waiting"
              }
          }
